version: '3'

services:
  app:
    image: 'ftracker:latest'
    build:
      context: .
    container_name: ftracker-api
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password123

  db:
    image: 'postgres:14-alpine'
    container_name: ftracker-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123